### ISSUE TITLE
Can't input token

### ISSUE THREAD

**Issue by Sengolda** [The-Coding-Academy/coding-bot-v4#15]
**Describe the bug**
When I run the git command given in the README.md file it works when I put the ID but doesn't paste the token

**Expected behavior**
I thought it would paste but it did not

**Discord Version**:
Desktop - App
version: Stable 82705 (15996b1)

**Additional context**
Python version: 3.9

**Comment by BobDotCom** [comment]
What operating system?

**Comment by Sengolda** [comment]
> What operating system?

MacOS

**Comment by BobDotCom** [comment]
I made it so that when you paste the token, it doesnt show inside the terminal. it works kind of like a password, it is hidden. Try running the setup command and paste your token in, then hit enter. Once the command finishes, you can check by running `cat .env` and you should see the contents of the file, and your token should be in there.
